// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockCartApi.Data;

#nullable disable

namespace StockCartApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907134905_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockCartApi.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("StockCartApi.Models.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("StockCartApi.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Name = "สบู่ก้อนนกแก้ว (สีเขียว)",
                            Price = 15m,
                            Sku = "ITM-001"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Name = "ยาสีฟันคอลเกต 150g",
                            Price = 45m,
                            Sku = "ITM-002"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Name = "แชมพูซันซิล 400ml",
                            Price = 129m,
                            Sku = "ITM-003"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Name = "ผงซักฟอกบรีส เอกเซล 1500g",
                            Price = 145m,
                            Sku = "ITM-004"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Name = "น้ำยาล้างจานซันไลต์ 800ml",
                            Price = 42m,
                            Sku = "ITM-005"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Name = "กระดาษทิชชู่ Scott (แพ็ค 6 ม้วน)",
                            Price = 89m,
                            Sku = "ITM-006"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Name = "น้ำดื่มคริสตัล 1.5 ลิตร",
                            Price = 15m,
                            Sku = "ITM-007"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Name = "บะหมี่กึ่งสำเร็จรูป มาม่าหมูสับ",
                            Price = 7m,
                            Sku = "ITM-008"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000009"),
                            Name = "ปลากระป๋องสามแม่ครัว",
                            Price = 20m,
                            Sku = "ITM-009"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000010"),
                            Name = "สมุดโน้ตริมลวด A5",
                            Price = 35m,
                            Sku = "ITM-010"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000011"),
                            Name = "ปากกาลูกลื่นสีน้ำเงิน (แพ็ค 3 ด้าม)",
                            Price = 25m,
                            Sku = "ITM-011"
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000012"),
                            Name = "ถ่านอัลคาไลน์ AA (แพ็ค 4 ก้อน)",
                            Price = 75m,
                            Sku = "ITM-012"
                        });
                });

            modelBuilder.Entity("StockCartApi.Models.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Quantity = 30
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Quantity = 25
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000004"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Quantity = 20
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000005"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000006"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Quantity = 100
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000007"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Quantity = 200
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000008"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Quantity = 150
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000009"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            Quantity = 60
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000010"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000010"),
                            Quantity = 15
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000011"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000011"),
                            Quantity = 80
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000012"),
                            ProductId = new Guid("a0000000-0000-0000-0000-000000000012"),
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("StockCartApi.Models.OrderDetail", b =>
                {
                    b.HasOne("StockCartApi.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockCartApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockCartApi.Models.Stock", b =>
                {
                    b.HasOne("StockCartApi.Models.Product", "Product")
                        .WithOne("Stock")
                        .HasForeignKey("StockCartApi.Models.Stock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockCartApi.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("StockCartApi.Models.Product", b =>
                {
                    b.Navigation("Stock");
                });
#pragma warning restore 612, 618
        }
    }
}
